export const DEFAULT_OFFER_COUNT = 15;
export const DEFAULT_OFFER_MAX_LIMIT = 60;
export const DEFAULT_DISCUSSED_OFFER_COUNT = 5;
export const DEFAULT_NEW_OFFER_COUNT = 5;
export const DEFAULT_PREMIUM_BY_TOWN_MAX_LIMIT = 3;
